### ISSUE TITLE
The evaluation 

### ISSUE THREAD

**Issue by saja1994** [soujanyaporia/aspect-extraction#6]
Hello

First of all, thank you for your effort. I have a question about the model's evaluation, what is the difference between chunk-based evaluation and partial matching based evaluation? and why there is a huge difference between their results? I am using the F1 measure for the evaluation of my dataset and got very different results.

Also, I want to ask you if there is any paper to cite the window-CNN+maxpool+CRF model?

Thanks,

**Comment by soujanyaporia** [comment]
The chunk-based evaluation checks whether the whole aspect is detected correctly. 

Please cite this paper for the window-CNN+maxpool+CRF model - Poria, S., Cambria, E. and Gelbukh, A., 2016. Aspect extraction for opinion mining with a deep convolutional neural network. Knowledge-Based Systems, 108, pp.42-49.
